# Apollo Config
app:
  # Apollo的AppId(类似ACM中的DataId)
  id: services
apollo:
  # apollo_meta需配置在环境变量中
  meta: ${apollo_meta:http://apolloconfig.dev.wyyt:8640/}
  bootstrap:
    enabled: true
    namespaces: Architecture.spring-cloud-common,application
    eagerLoad:
      enabled: true

server:
  port: 1000

spring:
  application:
    name: @project.artifactId@
    group: @project.artifactId@
    # 版本号, 使用发布的时间作为版本号, 精确到分钟, 格式: yyyyMMddHHmmss
    version: 20210101010100
    strategy:
      scan:
        # 指定对业务RestController类的扫描路径。此项配置作用于RPC方式的调用拦截、消费端的服务隔离和调用链三项功能
        packages: @project.artifactId@
  cloud:
    consul:
      host: ${consul_host}
      port: ${consul_port}
  zipkin:
    base-url: ${zipkin_url}
    sender:
      type: web