app:
  id: spring-cloud-gateway
apollo:
  meta: ${apollo_meta:http://apolloconfig.dev.wyyt:8640/}
  bootstrap:
    enabled: true
    namespaces: Architecture.spring-cloud-common,application
    eagerLoad:
      enabled: true

server:
  port: 80

spring:
  application:
    name: ${gateway_consul_name}
    group: ${gateway_consul_group}
    version: 1.0