#Apollo Config
app:
  id: services
apollo:
  meta: ${apollo_meta:http://apolloconfig.dev.wyyt:8640/}
  bootstrap:
    enabled: true
    namespaces: application
    eagerLoad:
      enabled: true

server:
  port: 3002

spring:
  application:
    name: c
    group: scfs
    version: 1.2
    strategy:
      scan:
        # RestController类的扫描路径
        packages: org.wyyt
  cloud:
    consul:
      host: ${consul_host:192.168.5.21}
      port: ${consul_port:8500}
  zipkin:
    base-url: ${zipkin_url:http://192.168.6.167:9411}