# Apollo Config
app:
  # Apollo的AppId(类似ACM中的DataId)
  id: services
apollo:
  # apollo_meta需配置在环境变量中
  meta: ${apollo_meta:http://apolloconfig.dev.wyyt:8640/}
  bootstrap:
    enabled: true
    namespaces: Architecture.spring-cloud-common,application
    eagerLoad:
      enabled: true

server:
  port: 1002

spring:
  application:
    name: a
    group: sample-group
    version: 1.2
    strategy:
      scan:
        # RestController类的扫描路径
        packages: org.wyyt