# Apollo Config
app:
  # Apollo的AppId(类似ACM中的DataId)
  id: services
apollo:
  # apollo_meta需配置在环境变量中
  meta: ${apollo_meta:http://apolloconfig.dev.wyyt:8640/}
  bootstrap:
    enabled: true
    namespaces: Architecture.spring-cloud-common,application
    eagerLoad:
      enabled: true

server:
  port: 1001

spring:
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 10MB
  application:
    name: a
    group: sample-group
    version: 202101181601
    strategy:
      scan:
        # 指定对业务RestController类的扫描路径。此项配置作用于RPC方式的调用拦截、消费端的服务隔离和调用链三项功能
        packages: springcloud.service.demo
  cloud:
    consul:
      host: ${consul_host}
      port: ${consul_port}
  zipkin:
    #    base-url: ${zipkin_url}
    sender:
      type: kafka
  kafka:
    bootstrap-servers: 192.168.6.164:9092,192.168.6.165:9092,192.168.6.166:9092