app:
  id: spring-boot-admin
apollo:
  meta: ${apollo_meta:http://apolloconfig.dev.wyyt:8640/}
  bootstrap:
    enabled: true
    namespaces: Architecture.spring-cloud-common,Architecture.gateway,Architecture.gateway,application
    eagerLoad:
      enabled: true

spring:
  application:
    name: spring-boot-admin-server
  cloud:
    config:
      enabled: false
    consul:
      host: ${consul_host}
      port: ${consul_port}
      discovery:
        service-name: ${spring.application.name}
        prefer-ip-address: true
        # ip-address: 192.168.12.155
  boot:
    admin:
      discovery:
        ignored-services: consul,${spring.application.name}
      ui:
        title: SpringBootCloud服务
        brand: <img src="assets/img/icon-spring-boot-admin.svg"><span>SpringBoot Cloud</span>
        available-languages:
          - zh-CN
          - en
  security:
    user:
      name: admin
      password: admin
  redis:
    host: ${redis_host}
    port: ${redis_port}
    password: ${redis_password}
    timeout: ${redis_timeout}
    database: ${redis_database}
    jedis:
      pool:
        max-active: ${redis-max-active}
        max-idle: ${redis-max-idle}
        min-idle: ${redis-min-idle}
  thymeleaf:
    check-template-location: false

server:
  port: ${server_port:83}
  tomcat:
    uri-encoding: UTF-8
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,application/xml
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

ribbon:
  eager-load:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

dingtalk:
  enabled: ${dingtalk_enabled:false}
  accessToken: ${dingtalk_accessToken}
  secret: ${dingtalk_secret}
