spring:
  application:
    name: spring-boot-admin-server
  cloud:
    config:
      enabled: false
    consul:
      host: ${consul_host:192.168.5.21}
      port: ${consul_port:8500}
      discovery:
        service-name: ${spring.application.name}
        prefer-ip-address: true
        # ip-address: 192.168.12.155
  boot:
    admin:
      discovery:
        ignored-services: consul,${spring.application.name}
      ui:
        title: SpringBootCloud服务
        brand: <img src="assets/img/icon-spring-boot-admin.svg"><span>SpringBootCloud</span>
        available-languages:
          - zh-CN
          - en
  security:
    user:
      name: admin
      password: admin

server:
  port: ${app_port:80}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

app:
  id: spring-boot-admin
apollo:
  meta: ${apollo_meta:http://192.168.12.155:8080/}
  bootstrap:
    enabled: true
    namespaces: application
    eagerLoad:
      enabled: true

dingtalk:
  enabled: ${dingtalk_enabled:false}
  accessToken: ${dingtalk_accessToken}
  secret: ${dingtalk_secret}