app:
  id: spring-cloud-auth
apollo:
  meta: ${apollo_meta:http://apolloconfig.dev.wyyt:8640/}
  bootstrap:
    enabled: true
    namespaces: Architecture.spring-cloud-common,Architecture.gateway,Architecture.gateway,application
    eagerLoad:
      enabled: true

server:
  port: 82

spring:
  application:
    name: ${auth_consul_name}
    group: ${auth_consul_group}
    version: 1.0
    strategy:
      scan:
        # 指定对业务RestController类的扫描路径。此项配置作用于RPC方式的调用拦截、消费端的服务隔离和调用链三项功能
        packages: org.wyyt.springcloud.auth
  cloud:
    consul:
      host: ${consul_host}
      port: ${consul_port}
  zipkin:
    base-url: ${zipkin_url}
    sender:
      type: web
  redis:
    host: ${redis_host}
    port: ${redis_port}
    password: ${redis_password}
    timeout: ${redis_timeout}
    database: ${redis_database}
    jedis:
      pool:
        max-active: ${redis-max-active}
        max-idle: ${redis-max-idle}
        min-idle: ${redis-min-idle}